### ISSUE TITLE
AttributeError: 'PhysicalNetwork' object has no attribute 'degree_benchmark'. Did you mean: 'get_degree_benchmark'?

### ISSUE THREAD

**Issue by lpj12121** [GeminiLight/hrl-acra#3]
I want to use a real network to verify the baseline algorithm. I set file_path: './dataset/topology/Brain.gml' in p_net_setting.yaml. After running the command to test the baseline algorithm, the following error occurred.

*** Generate virtual networks with seed 0
Running with a3c_gcn in epoch 0:   0%|                                                                                                                    | 0/1000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "D:\hrl-acra-main\main.py", line 29, in <module>
    run(config)
  File "D:\hrl-acra-main\main.py", line 16, in run
    scenario.run()
  File "D:\hrl-acra-main\base\scenario.py", line 94, in run
    solution = self.solver.solve(instance)
  File "D:\hrl-acra-main\solver\learning\rl_solver.py", line 101, in solve
    sub_env = self.SubEnv(p_net, v_net, self.controller, self.recorder, self.counter, **self.basic_config)
  File "D:\hrl-acra-main\solver\learning\a3c_gcn\sub_env.py", line 10, in __init__
    super(SubEnv, self).__init__(p_net, v_net, controller, recorder, counter, **kwargs)
  File "D:\hrl-acra-main\solver\learning\sub_rl_environment.py", line 127, in __init__
    super(JointPRStepSubRLEnv, self).__init__(p_net, v_net, controller, recorder, counter, **kwargs)
  File "D:\hrl-acra-main\solver\learning\sub_rl_environment.py", line 19, in __init__
    super(SubRLEnv, self).__init__(**kwargs)
  File "D:\hrl-acra-main\solver\learning\rl_environment.py", line 23, in __init__
    self.degree_benchmark = self.p_net.degree_benchmark
AttributeError: 'PhysicalNetwork' object has no attribute 'degree_benchmark'. Did you mean: 'get_degree_benchmark'?

Running is a3c_gcn.

What causes this?

**Comment by GeminiLight** [comment]
Please fix this issue by replacing `degree_benchmark` with `get_degree_benchmark`.

This may be attributed to the loading of an uninitialized Physical Network.

**Comment by lpj12121** [comment]
> Please fix this issue by replacing `degree_benchmark` with `get_degree_benchmark`.
> 
> This may be attributed to the loading of an uninitialized Physical Network.

Thank you very much, but I encountered a new problem, in issue 4
